#!/usr/bin/env python3
"""Build the Gate C8 Genome Medicine submission sources from the Gate C7 freeze."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "01_manuscript" / "manuscript_v9_gateC7_submission_scientific_draft_2026-08-20.md"
RUN_DIR = ROOT / "phase17_v7" / "gateC8" / "20260820_genome_medicine_submission_package"
REF_DIR = RUN_DIR / "references"
SUBMISSION = ROOT / "04_submission"
PACKAGE = SUBMISSION / "package_genome_medicine_gateC8_2026-08-20"


def section(text: str, start: str, end: str | None) -> str:
    start_marker = f"## {start}"
    begin = text.index(start_marker) + len(start_marker)
    finish = text.index(f"## {end}", begin) if end else len(text)
    return text[begin:finish].strip()


def words(text: str) -> int:
    plain = re.sub(r"[`*_#|\[\]]", " ", text)
    return len(re.findall(r"\b[\w'-]+\b", plain))


def wrap_paragraphs(text: str) -> str:
    blocks = re.split(r"\n\s*\n", text.strip())
    output = []
    for block in blocks:
        if block.startswith("### ") or block.startswith("## ") or block.startswith("-") or re.match(r"^\d+\. ", block):
            output.append(block)
        else:
            output.append(re.sub(r"\s*\n\s*", " ", block).strip())
    return "\n\n".join(output)


def main() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    PACKAGE.mkdir(parents=True, exist_ok=True)
    source = SOURCE.read_text(encoding="utf-8-sig")
    results = wrap_paragraphs(section(source, "Results", "Discussion"))
    discussion = wrap_paragraphs(section(source, "Discussion", "Methods"))
    methods = wrap_paragraphs(section(source, "Methods", "Figure legends"))
    legends = wrap_paragraphs(section(source, "Figure legends", "Data and code availability"))

    conclusion = (
        "The defensible advance is therefore specific: SLE is associated with an independently "
        "replicated IFN transcriptional shift within a disease-blind broad conventional-B "
        "compartment, accompanied by convergent IFN-centred regulatory and perturbational "
        "evidence. This conclusion is stronger than a single-cohort differential-expression "
        "result and narrower than a causal mechanism claim."
    )
    discussion = discussion.replace(conclusion, "").strip()

    methods = methods.replace(
        "GSE174188 was used",
        "GSE174188 [1,14] was used",
    ).replace(
        "GSE135779 was the independent",
        "GSE135779 [2,15] was the independent",
    ).replace(
        "GSE23307 supplied",
        "GSE23307 [13,16] supplied",
    ).replace(
        "GSE163121 was reserved for directional boundary analysis and OneK1K for healthy reference context; neither contributes to the central replication claim reported here.",
        "Resources not contributing to the central replication claim were excluded from the active manuscript.",
    )
    methods = methods.replace(
        "Unintegrated and Harmony-adjusted representations",
        "Unintegrated Scanpy [6] and Harmony-adjusted [7] representations",
    ).replace("Leiden solutions", "Leiden [8] solutions")
    methods = methods.replace(
        "Genes were filtered with edgeR `filterByExpr`",
        "Genes were filtered with edgeR [9] `filterByExpr`",
    )
    methods = methods.replace(
        "Human CollecTRI interactions were retrieved from OmniPath",
        "Human CollecTRI interactions [10,11] were retrieved from OmniPath",
    )
    methods = methods.replace(
        "MSigDB human release 2026.1.Hs Hallmark set",
        "MSigDB [12] human release 2026.1.Hs Hallmark set",
    )
    methods = methods.replace(
        "GSE23307 GPL6104 microarray profiles",
        "GSE23307 [13,16] GPL6104 microarray profiles",
    ).replace("residual-risk- negative", "residual-doublet-risk-negative")
    methods = methods.replace(
        "### Reproducibility and governance",
        "### Generative AI assistance\n\nOpenAI Codex was used during project development for code drafting, workflow documentation, language editing and generation of quality-control checks. All computations were executed locally against frozen inputs; numerical results were read from machine-generated analysis outputs rather than generated by the language model. The authors reviewed the scripts, outputs, interpretations and final text and remain accountable for the work. No AI system is listed as an author.\n\n### Reproducibility and governance",
    )

    background = """Systemic lupus erythematosus (SLE) is a heterogeneous autoimmune disease involving loss of B-cell tolerance, autoantibody production and sustained innate immune activation. Peripheral-blood single-cell studies have described changes in naive, memory, double-negative, CD11c-positive and antibody-secreting B-cell populations together with prominent type I interferon responses [1,2]. However, a larger fraction of cells assigned to a state and increased gene expression within that state are biologically distinct phenomena.

Single-cell disease studies are particularly vulnerable to pseudoreplication when cells, rather than donors or biological samples, are treated as independent units [3,4]. Composition introduces an additional constraint because an increase in one compartment changes the observed fractions of all others [5]. Public SLE resources also distribute samples across processing cohorts, include repeated donors and provide uneven disease-group support within technical strata. Outcome-informed cluster labels or pooled cell-level tests can therefore combine biology with design structure.

We addressed these problems through a staged secondary analysis. Raw-count integrity, metadata hierarchy and disease-by-cohort support were audited first. B-lineage identity was reconstructed while protected disease fields remained separate. Only after a disease-blind identity model was frozen were sample-level composition and within-compartment transcription tested. The primary expression result was then carried into independent GSE135779 under a pre-effect mapping and analysis contract.

The analysis was designed to distinguish robust process-level biology from unstable subtype narratives. We tested whether fine B-cell partitions were reproducible enough for hard outcome inference, whether antibody-secreting-cell abundance represented a primary disease result and whether a frozen transcriptional program replicated across datasets. Finally, we used a prespecified TF-target family and two orthogonal response resources to evaluate convergent regulatory support without converting association into a causal claim."""

    abstract_sections = {
        "Background": "SLE alters both the abundance and transcriptional state of peripheral B cells, but these layers can be conflated by outcome-informed annotation, cell-level inference and technically imbalanced cohorts.",
        "Methods": "We performed a donor- and cohort-resolved reanalysis of public single-cell RNA-sequencing data. B-lineage identity was reconstructed without disease labels in GSE174188 before sample-level composition and sample-by-compartment pseudobulk testing. A frozen program was evaluated in independent GSE135779, followed by a prespecified 24-test CollecTRI family, MSigDB M5911 enrichment and paired IFN-beta perturbation profiles from GSE23307.",
        "Results": "Among 150,402 quality-controlled GSE174188 B-lineage cells, resampling supported broad conventional-B (B_CONV) and antibody-secreting-cell (B_ASC) compartments but not stable hard naive-memory subtypes. Primary B_ASC relative abundance was not associated with SLE (odds ratio 0.947, 95% confidence interval 0.636-1.410; P=0.787). Within B_CONV, the prespecified IFN/ISG program increased in the primary contrast (effect 0.837, 95% confidence interval 0.525-1.148; q=2.98 x 10^-6), a donor-nonoverlap internal contrast (effect 1.086; q=3.61 x 10^-4) and independent GSE135779 childhood donors (11 controls and 32 SLE; effect 1.042, 95% confidence interval 0.681-1.402; q=2.98 x 10^-6). All ten jointly tested IFN genes were positive despite low genome-wide agreement (Spearman rho=0.026). STAT1 and STAT2 target activities were positive and globally significant in all three contrasts and robust to target deletion and resampling. M5911 was enriched in all contrasts, and IFN-beta exposure increased all 12 frozen genes in each of two healthy-donor profiles.",
        "Conclusions": "SLE shows independently replicated IFN remodeling within a disease-blind broad conventional-B compartment, with convergent observational regulatory evidence. The results do not establish a discrete subtype, causal regulator or unique upstream stimulus.",
    }
    abstract = "\n\n".join(f"**{name}:** {body}" for name, body in abstract_sections.items())
    if words(abstract) > 350:
        raise RuntimeError(f"Structured abstract exceeds 350 words: {words(abstract)}")

    references = (REF_DIR / "references_gateC8_vancouver.md").read_text(encoding="utf-8").strip()
    references += """
14. National Center for Biotechnology Information. Gene Expression Omnibus series GSE174188. https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE174188. Accessed 20 Aug 2026.
15. National Center for Biotechnology Information. Gene Expression Omnibus series GSE135779. https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE135779. Accessed 20 Aug 2026.
16. National Center for Biotechnology Information. Gene Expression Omnibus series GSE23307. https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE23307. Accessed 20 Aug 2026.
17. SLE B-cell remodeling analysis repository. GitHub. https://github.com/1209433622cz-maker/sle-bcell-remodeling. Accessed 20 Aug 2026."""

    title = "Disease-blind single-cell reconstruction identifies replicated interferon remodeling and convergent regulatory evidence in systemic lupus erythematosus B cells"
    manuscript = f"""# {title}

**Article type:** Research

**Authors:** Zhi Chen [1] and Teng Qi [1,*]

**Affiliation 1:** School of Medicine, The Chinese University of Hong Kong, Shenzhen, Shenzhen 518172, China

**Corresponding author:** Teng Qi, School of Medicine, The Chinese University of Hong Kong, Shenzhen, MED Start-up Building, 2001 Longxiang Boulevard, Longgang District, Shenzhen 518172, China; tengqi@link.cuhk.edu.cn

**ORCID identifiers:** Zhi Chen, https://orcid.org/0009-0001-0072-5576; Teng Qi, https://orcid.org/0009-0007-7648-4776

**Author emails:** Zhi Chen, zhichen1@link.cuhk.edu.cn; Teng Qi, tengqi@link.cuhk.edu.cn

**Running title:** Replicated IFN remodeling in SLE B cells

**Version:** Gate C8 Genome Medicine submission draft v10

**Date:** 20 August 2026

## Abstract

{abstract}

## Keywords

systemic lupus erythematosus; B cells; single-cell RNA sequencing; pseudobulk; interferon; independent validation; transcription-factor activity; reproducibility

## Background

{background}

## Methods

{methods}

## Results

{results}

## Discussion

{discussion}

## Conclusions

{conclusion}

## List of abbreviations

**ASC:** antibody-secreting cell; **B_ASC:** disease-blind antibody-secreting-cell compartment; **B_CONV:** disease-blind broad conventional-B compartment; **FDR:** false discovery rate; **GEO:** Gene Expression Omnibus; **HC1/HC3:** heteroskedasticity-consistent covariance estimators; **IFN:** interferon; **ISG:** interferon-stimulated gene; **NES:** normalized enrichment score; **SLE:** systemic lupus erythematosus; **TF:** transcription factor; **TMM:** trimmed mean of M values; **UMI:** unique molecular identifier.

## Declarations

### Ethics approval and consent to participate

This secondary study used publicly available, de-identified human transcriptomic data and recruited no participants or new specimens. [[AUTHOR/INSTITUTION CONFIRMATION REQUIRED: state whether additional institutional review was not required, exempt or waived; provide committee name and reference number if applicable.]] Ethics approval and consent procedures for the source studies are reported in the original publications [1,2,13].

### Consent for publication

Not applicable; the manuscript contains no identifiable individual participant information.

### Availability of data and materials

The datasets analysed are publicly available through NCBI GEO under GSE174188, GSE135779 and GSE23307 [14-16]. Analysis scripts, machine-readable decisions and compact derived source-data tables are available in the project repository [17], frozen for this draft at commit `05d5d60`. [[PRE-SUBMISSION ACTION REQUIRED: add an open-source licence and an immutable Zenodo or equivalent archive DOI.]] Large recomputable matrices are not duplicated from their source repositories.

### Competing interests

[[AUTHOR COMPLETION REQUIRED: either declare all financial and non-financial competing interests by author initials or state, after all-author confirmation, that the authors declare no competing interests.]]

### Funding

[[AUTHOR COMPLETION REQUIRED: list funder names, grant numbers, recipient initials and funder roles, or state that the research received no specific funding.]]

### Authors' contributions

[[AUTHOR COMPLETION REQUIRED: map author initials to CRediT roles and confirm that all authors read and approved the final manuscript.]]

### Acknowledgements

[[AUTHOR COMPLETION REQUIRED: list contributors with permission, or state "Not applicable".]]

### Authors' information

Zhi Chen is an MSc student in Bioinformatics at The Chinese University of Hong Kong, Shenzhen. His research focuses on multi-omics integration, clinical cancer research and analysis of the tumour microenvironment. He holds a BSc in Biomedical Sciences from Queen Mary University of London and an MB in Clinical Medicine from Nanchang University. Teng Qi is an MSc student in Bioinformatics at The Chinese University of Hong Kong, Shenzhen.

## Additional files

**Additional file 1 (.docx):** Supplementary information. Extended governance, evidence-boundary and reproducibility tables supporting the disease-blind reconstruction, sample-level composition, pseudobulk replication and regulatory analyses.

**Additional file 2 (.zip):** Figure source data. Machine-readable CSV files underlying Figures 1-5, with a SHA-256 manifest.

## Figure legends

{legends}

## References

{references}
"""
    manuscript_path = ROOT / "01_manuscript" / "manuscript_v10_genome_medicine_submission_2026-08-20.md"
    manuscript_path.write_text(manuscript, encoding="utf-8")

    supplement = """# Supplementary information

## Disease-blind single-cell reconstruction identifies replicated interferon remodeling and convergent regulatory evidence in systemic lupus erythematosus B cells

**Version:** Gate C8, 20 August 2026

**Authors:** Zhi Chen and Teng Qi

## Supplementary overview

This file documents the prespecified governance, identity boundary, inferential units, validation hierarchy and reproducibility assets supporting the main manuscript. It does not introduce post hoc disease-defined cell states or new claims beyond the Gate C7 scientific freeze.

## Supplementary Methods 1 | Gate governance and outcome protection

The workflow used sequential gates for source integrity, hard quality control, disease-blind identity reconstruction, sample-level composition, within-compartment pseudobulk analysis, independent validation and external regulatory evidence. Protected disease fields were separated during identity reconstruction. Real outcome effects were unlocked only after the relevant input, mapping, contrast and statistical-engine contracts had been recorded. Each gate retained a machine-readable decision and SHA-256 integrity manifest.

## Supplementary Methods 2 | Identity stability boundary

The initial five-state model failed the prespecified resampling thresholds. Repair analyses evaluated four-, three- and two-level mappings without consulting disease labels. Only the broad B_CONV/B_ASC solution met all stability criteria across 20 resampling runs. Fine naive-memory structure was therefore retained as continuous transcriptional context rather than a hard publication subtype. This negative boundary is part of the result, not a quality-control artifact to be removed.

## Supplementary Methods 3 | Biological units and contrast hierarchy

GSE174188 composition and expression analyses used sample-by-processing-cohort strata; donor-aware sensitivities addressed repeated samples. GSE135779 used donors as the biological units. Primary, internal, donor-nonoverlap, secondary flare, childhood, combined and adult contrasts remained separate. No bridge stratum was used to manufacture a pooled disease coefficient, and internal GSE174188 estimates were not described as independent validation.

## Supplementary Methods 4 | Robustness and specificity

Prespecified sensitivity analyses varied minimum cell support, excluded residual-doublet-risk cells, deleted samples or donors one at a time, omitted source labels and compared platelet/ambient, ASC/UPR and pan-B control programs. The TF-target family used one global correction across 24 tests. STAT1 and STAT2 core results underwent leave-one-target and deterministic 80% target-resampling analyses. The GSE23307 two-donor perturbation remained descriptive.

## Supplementary Table S1 | Dataset roles and inferential units

| Resource | Role | Biological unit | Active scope |
|---|---|---|---|
| GSE174188 | Discovery and internal validation | Sample-cohort stratum; donor sensitivities | Disease-blind B_CONV/B_ASC identity, composition and B_CONV transcription |
| GSE135779 | Independent SLE validation | Donor | Broad conventional-B analog; childhood primary |
| CollecTRI/OmniPath | Curated regulator prior | Ranked genes within contrast | Prespecified eight-regulator, three-contrast family |
| MSigDB M5911 | Orthogonal response prior | Ranked genes within contrast | Hallmark interferon-alpha response enrichment |
| GSE23307 | Orthogonal perturbation support | Paired profile within donor | Descriptive IFN-beta response, n=2 donors |

## Supplementary Table S2 | Claim boundaries

| Supported | Not supported |
|---|---|
| Broad disease-blind B_CONV and B_ASC identity | Stable hard naive, memory or atypical subtypes |
| Null primary B_ASC relative-abundance result | General B_ASC expansion in SLE |
| Replicated IFN/ISG remodeling within B_CONV | Genome-wide shared disease transcriptome |
| Convergent STAT1/STAT2 target activity | Causal TF activation or direct binding |
| IFN-centred response evidence | A unique initiating IFN ligand in SLE |

## Supplementary Table S3 | Frozen quantitative anchors

| Analysis | Frozen result |
|---|---|
| Identity stability | minimum mapped ARI 0.990; minimum agreement 0.9998; minimum median Jaccard 0.991 |
| Primary B_ASC composition | odds ratio 0.947; 95% CI 0.636-1.410; P=0.787 |
| GSE174188 primary IFN/ISG | effect 0.837; 95% CI 0.525-1.148; q=2.98 x 10^-6 |
| GSE174188 donor-nonoverlap IFN/ISG | effect 1.086; q=3.61 x 10^-4 |
| GSE135779 childhood IFN/ISG | effect 1.042; 95% CI 0.681-1.402; q=2.98 x 10^-6 |
| Cross-dataset genome-wide agreement | 4,410 genes; Spearman rho=0.026 |
| M5911 enrichment | NES 3.187, 3.050 and 3.527 |
| GSE23307 perturbation | donor effects 3.294 and 3.666; 12/12 genes positive in each |

## Supplementary Table S4 | Figure and source-data map

| Figure | Frozen gate | Machine-readable source |
|---|---|---|
| Figure 1 | C2B4 identity freeze | Figure1_source_data.csv |
| Figure 2 | C3A composition decision | Figure2_source_data.csv |
| Figure 3 | C4B GSE174188 transcription | Figure3_source_data.csv |
| Figure 4 | C5B independent replication | Figure4_source_data.csv |
| Figure 5 | C6B regulatory framing | Figure5_source_data.csv |

## Supplementary Table S5 | Reproducibility contract

| Component | Frozen record |
|---|---|
| Gate C7 scientific audit | `phase17_v7/gateC7/20260820_manuscript_figure_integration/06_GATE_C7_FINAL_AUDIT.json` |
| Claim-number crosswalk | `phase17_v7/gateC7/20260820_manuscript_figure_integration/02_CLAIM_NUMBER_CROSSWALK.csv` |
| Figure-source crosswalk | `phase17_v7/gateC7/20260820_manuscript_figure_integration/03_FIGURE_SOURCE_CROSSWALK.csv` |
| Numeric-source crosswalk | `phase17_v7/gateC7/20260820_manuscript_figure_integration/04_MANUSCRIPT_NUMERIC_SOURCE.csv` |
| Active manuscript source | `01_manuscript/manuscript_v10_genome_medicine_submission_2026-08-20.md` |
| Repository commit inherited by Gate C8 | `05d5d60` |

## Supplementary note on superseded artifacts

Earlier manuscripts and figures remain in the repository for provenance but are not numerical sources for this submission. In particular, the previous ABC/APC-like hard-subtype narrative and untransformed GSE23307 outputs are superseded and excluded from every active claim, figure and submission file.
"""
    supplement_path = ROOT / "01_manuscript" / "supplementary_information_v1_gateC8_2026-08-20.md"
    supplement_path.write_text(supplement, encoding="utf-8")

    cover_letter = f"""# Cover letter

20 August 2026

Teng Qi\nSchool of Medicine\nThe Chinese University of Hong Kong, Shenzhen\nMED Start-up Building, 2001 Longxiang Boulevard\nLonggang District, Shenzhen 518172, China\ntengqi@link.cuhk.edu.cn

Editors\nGenome Medicine

Dear Editors,

Please consider our Research article, "{title}", for publication in Genome Medicine.

This study addresses a recurrent problem in disease single-cell genomics: cell identity, relative abundance and within-compartment transcription can be conflated when annotations are informed by outcomes or cells are treated as independent replicates. We reconstructed B-lineage identity without disease labels, retained biological samples or donors as inferential units and carried a frozen transcriptional result into an independent SLE dataset.

The principal advance is a deliberately bounded and reproducible result. Fine naive-memory partitions were not stable enough for hard outcome inference, and primary antibody-secreting-cell relative abundance was null. In contrast, a type I IFN/ISG program within broad conventional B cells reproduced in GSE174188 discovery, a donor-nonoverlap internal contrast and independent GSE135779 childhood donors. STAT1 and STAT2 target activities reproduced across all three contrasts under one prespecified 24-test correction family and remained positive under target-deletion and resampling analyses. Independent M5911 enrichment and paired IFN-beta perturbation profiles supplied orthogonal response evidence. We explicitly do not claim a discrete IFN-high subtype, causal regulator, direct TF binding or unique upstream ligand.

We believe the work fits Genome Medicine because it uses human single-cell genomics, independent disease-cohort validation and systems-level regulatory evidence to refine the level at which an immunogenomic SLE finding is reproducible. The staged, auditable design is also relevant beyond SLE to secondary analysis of technically imbalanced public single-cell cohorts.

All datasets are public and are cited by accession. Scripts, machine-readable decisions, figure source data and integrity manifests are versioned in the accompanying repository. [[PRE-SUBMISSION ACTION REQUIRED: insert immutable archive DOI and licence information.]]

[[AUTHOR CONFIRMATION REQUIRED: confirm that all authors approved the manuscript and its submission; that the work has not been published and is not under consideration elsewhere; and disclose any policy issues or competing interests.]]

Suggested reviewers and opposed reviewers, if any, will be supplied by the corresponding author through the submission system using verifiable institutional contact information.

Sincerely,

Teng Qi\nCorresponding author\ntengqi@link.cuhk.edu.cn
"""
    (SUBMISSION / "cover_letter_genome_medicine_gateC8_AUTHOR_COMPLETION_REQUIRED_2026-08-20.md").write_text(cover_letter, encoding="utf-8")

    author_form = """# Gate C8 author completion form

Complete and approve every hard-stop field before portal submission. Do not replace a bracketed item with an assumption.

## Author identity

- [x] Author order: Zhi Chen first author; Teng Qi corresponding author.
- [x] Author emails: zhichen1@link.cuhk.edu.cn; tengqi@link.cuhk.edu.cn.
- [x] Shared affiliation: School of Medicine, The Chinese University of Hong Kong, Shenzhen.
- [x] Corresponding author email and official institutional postal address.
- [x] ORCID: Zhi Chen 0009-0001-0072-5576; Teng Qi 0009-0007-7648-4776.
- Confirm that the two-person author list is complete and that the corresponding-author designation is intentional; document any non-author supervision or contribution for acknowledgement.
- CRediT roles mapped to author initials.
- Written confirmation that every author reviewed and approved the final files.

## Ethics and consent

- Institutional determination for secondary analysis of public de-identified human data: not required, exempt or waived.
- Committee name and reference number if applicable.
- Confirmation that no identifiable individual information appears in any file.

## Declarations

- Financial and non-financial competing interests for every author.
- Funder names, grant numbers, recipient initials and funder roles, or explicit no-specific-funding statement.
- Acknowledgements with permission, or "Not applicable".
- Confirmation that the generative-AI disclosure accurately describes the workflow.

## Repository release

- Select and add an open-source licence approved by the authors/institution.
- Create an immutable release and archive it in Zenodo or an equivalent repository.
- Insert the release DOI into the manuscript, cover letter, README and portal fields.
- Confirm that no restricted raw data, credentials or personal identifiers are present.

## Submission attestations

- The manuscript is not published or under consideration elsewhere.
- All authors approve submission to Genome Medicine.
- All authors approve the cover-letter statements.
- APC eligibility, institutional agreement or waiver strategy has been checked.
- Current institutional JCR/CAS classification has been verified if required for programme reporting.
"""
    (SUBMISSION / "author_completion_form_gateC8_2026-08-20.md").write_text(author_form, encoding="utf-8")

    strategy = """# Gate C8 journal target decision

**Decision date:** 20 August 2026

## Frozen route

1. **Primary submission: Genome Medicine.** Best alignment with the actual human disease-genomics and immunogenomics evidence stack. The official scope includes genomics and multi-omics applications to understand disease, including immunogenomics and systems medicine. The main editorial risk is broad-interest novelty in a public-data-only study.
2. **First transfer-ready backup: Communications Biology.** Appropriate for a technically sound, well-supported biological advance important to a specialist community. Reformatting is manageable from the five-figure package.
3. **Disease-specialist backup: Journal of Autoimmunity.** Strong topical fit, but likely to press harder for direct functional mechanism.
4. **Reach only after new functional evidence: Nature Communications.** The present package is rigorous, but without matched patient perturbation, direct binding or prospective validation, the broad conceptual-advance threshold makes this an inefficient first submission.

## Genome Medicine requirements frozen into Gate C8

- Research article with significant new findings and broad interest.
- Structured Background/Methods/Results/Conclusions abstract, maximum 350 words.
- Three to ten keywords.
- Background, Methods, Results, Discussion and Conclusions.
- Full Declarations section, including ethics, consent, data, competing interests, funding, contributions and acknowledgements.
- Double-line spacing, line numbering and page numbering.
- Figure titles no longer than 15 words, legends no longer than 300 words and individual figure files below 10 MB.
- Editable manuscript and machine-readable supporting data.

Official sources checked 20 August 2026:

- https://link.springer.com/journal/13073/aims-and-scope
- https://link.springer.com/journal/13073/submission-guidelines
- https://link.springer.com/journal/13073/submission-guidelines/research
- https://www.nature.com/commsbio/aims
- https://www.nature.com/commsbio/submit/submission-guidelines
- https://www.nature.com/ncomms/submit/article

## Classification caveat

No JCR quartile or CAS category is asserted in this decision file. Those classifications are subscription-dependent and may change annually; the submitting institution must verify the current edition before using them in programme records.
"""
    (SUBMISSION / "journal_target_decision_gateC8_2026-08-20.md").write_text(strategy, encoding="utf-8")

    checklist = """# Genome Medicine Gate C8 reporting and submission checklist

## Scientific package

- [x] Gate C7 scientific freeze passed.
- [x] Five active figures map to frozen gates and source data.
- [x] Central claim is independent IFN/ISG replication within broad B_CONV.
- [x] Primary B_ASC composition remains a null boundary.
- [x] Regulatory language remains observational and non-causal.
- [x] Superseded ABC/APC-like and untransformed GSE23307 outputs are excluded.

## Journal structure

- [x] Structured abstract is at most 350 words and has no references.
- [x] Eight keywords are provided.
- [x] Required main sections and Declarations headings are present.
- [x] Figure title and legend limits are audited.
- [x] Double spacing, page numbering and continuous line numbering are encoded in DOCX.
- [x] Vancouver-style references are generated from verified DOI metadata.

## Files

- [x] Editable main manuscript DOCX.
- [x] Supplementary information DOCX.
- [x] Cover letter DOCX.
- [x] Figures 1-5 as separate composite PDF and 600-dpi PNG files.
- [x] Figure source-data ZIP and checksum manifest.
- [x] Rendered PDF review copies and page-image QA.

## Author hard stops

- [x] Author list/order, affiliations, emails, corresponding author and ORCID completed.
- [ ] Institutional ethics determination inserted.
- [ ] Competing interests, funding, contributions and acknowledgements approved.
- [ ] All-author submission and originality attestations approved.
- [ ] Open-source licence and immutable archive DOI added.
- [ ] APC/institutional agreement checked.

**Current status:** scientific and technical package may pass Gate C8, but portal submission remains blocked until every author hard stop is cleared.
"""
    (SUBMISSION / "reporting_checklist_gateC8_2026-08-20.md").write_text(checklist, encoding="utf-8")

    summary = {
        "created_at": "2026-08-20",
        "target": "Genome Medicine",
        "article_type": "Research",
        "manuscript": str(manuscript_path.relative_to(ROOT)).replace("\\", "/"),
        "supplement": str(supplement_path.relative_to(ROOT)).replace("\\", "/"),
        "abstract_words": words(abstract),
        "keywords": 8,
        "reference_count": 17,
        "author_identity_complete": True,
        "author_declarations_complete": False,
        "archive_doi_complete": False,
        "scientific_source": str(SOURCE.relative_to(ROOT)).replace("\\", "/"),
    }
    (RUN_DIR / "01_GATE_C8_SOURCE_BUILD_STATUS.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
